# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Summary: run Pytest suite against stable & dev releases of Cirq nightly.

name: Nightly tests
run-name: 'Run OpenFermion Pytest suite with stable & dev releases of Cirq'

on:
  schedule:
    - cron: '15 2 * * *'

  # Allow manual invocation.
  workflow_dispatch:
    inputs:
      debug:
        description: 'Run with debugging options'
        type: boolean
        default: true

# Declare default workflow permissions as read only.
permissions: read-all

# In case of manual invocation, cancel any previously-started runs.
concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  Pytest:
    # Try to fit as much info as possible into the GHA sidebar at run-time.
    name: Py ${{matrix.python}} + ${{matrix.os}}/${{matrix.arch}} + ${{matrix.cirq}}
    runs-on: ${{matrix.os}}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # These Python versions were carefully selected by trial and error
        # to be available on as many os/arch combos as possible, while also
        # making all necessary Python dependencies available on those combos.
        python: ['3.11.9', '3.12.8', '3.13.1']
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-14, windows-2025]
        cirq: ['cirq-core', 'cirq-core~=1.0.dev0']
        arch: [x64, arm64]
        exclude:
          - os: ubuntu-24.04
            arch: arm64

          - os: ubuntu-24.04-arm
            arch: x64

          # MacOS 14 is only available for arm64.
          - os: macos-14
            arch: x64

          # MacOS 15 is only available for arm64.
          - os: macos-15
            arch: x64

          # Windows 2025 is only available for x64.
          - os: windows-2025
            arch: arm64

    steps:
      - name: Check out a copy of the OpenFermion git repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        id: cache
        with:
          python-version: ${{matrix.python}}
          architecture: ${{matrix.arch}}
          cache: pip
          cache-dependency-path: dev_tools/requirements/envs/pytest.env.txt

      - name: Install OpenFermion Python requirements
        run: pip install -r dev_tools/requirements/envs/pytest.env.txt

      - name: Install ${{matrix.cirq}}
        run: pip install -U ${{matrix.cirq}}

      - name: Set up Pytest output problem matcher
        run: echo '::add-matcher::.github/problem-matchers/pytest.json'

      - name: Run Pytest
        run: check/pytest ${{inputs.debug && '-v' || '' }}

      - name: Print debugging info upon job failure
        if: ${{failure() || inputs.debug == true}}
        shell: bash
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
          RUNNER_CONTEXT: ${{toJson(runner)}}
          MATRIX_CONTEXT: ${{toJson(matrix)}}
          STRATEGY_CONTEXT: ${{toJson(strategy)}}
        run: |
          echo '::group:: Shell environment'
          env
          echo '::endgroup::'
          echo '::group:: Installed Python packages'
          pip list
          echo '::endgroup::'
          echo '::group:: GitHub context'
          echo "The job_id is: $GITHUB_JOB"
          echo "The id of this action is: $GITHUB_ACTION"
          echo "The run id is: $GITHUB_RUN_ID"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "$GITHUB_CONTEXT"
          echo '::endgroup::'
          echo '::group:: GitHub runner context'
          echo "$RUNNER_CONTEXT"
          echo '::endgroup::'
          echo '::group:: Matrix context'
          echo "$MATRIX_CONTEXT"
          echo '::endgroup::'
          echo '::group:: Strategy context'
          echo "$STRATEGY_CONTEXT"
          echo '::endgroup::'
